-- ============================================================
-- Camada Gold: adiciona Chaves Estrangeiras em FACT_TRIP
-- ============================================================

ALTER TABLE TAXI_NYC.TAXI_GOLD.FACT_TRIP
    ADD CONSTRAINT FK_FACT_TRIP_DATE
    FOREIGN KEY (DATE_ID) REFERENCES TAXI_NYC.TAXI_GOLD.DIM_DATA(DATE_ID);

ALTER TABLE TAXI_NYC.TAXI_GOLD.FACT_TRIP
    ADD CONSTRAINT FK_FACT_TRIP_PICKUP_LOCATION
    FOREIGN KEY (PICKUP_LOCATION_ID) REFERENCES TAXI_NYC.TAXI_GOLD.DIM_LOCATION(LOCATION_ID);

ALTER TABLE TAXI_NYC.TAXI_GOLD.FACT_TRIP
    ADD CONSTRAINT FK_FACT_TRIP_DROPOFF_LOCATION
    FOREIGN KEY (DROPOFF_LOCATION_ID) REFERENCES TAXI_NYC.TAXI_GOLD.DIM_LOCATION(LOCATION_ID);

ALTER TABLE TAXI_NYC.TAXI_GOLD.FACT_TRIP
    ADD CONSTRAINT FK_FACT_TRIP_PAYMENT
    FOREIGN KEY (PAYMENT_ID) REFERENCES TAXI_NYC.TAXI_GOLD.DIM_PAYEMENT(PAYMENT_ID);

ALTER TABLE TAXI_NYC.TAXI_GOLD.FACT_TRIP
    ADD CONSTRAINT FK_FACT_TRIP_VENDOR
    FOREIGN KEY (VENDOR_ID_SURROGATE) REFERENCES TAXI_NYC.TAXI_GOLD.DIM_VENDOR(VENDOR_ID_SURROGATE);

-- ============================================================
-- Camada Gold DML: carga de FACT_TRIP
-- Faz join da Silver com todas as dimensões para resolver as chaves substitutas.
-- ============================================================

INSERT INTO TAXI_NYC.TAXI_GOLD.FACT_TRIP (
    DATE_ID,
    PICKUP_LOCATION_ID,
    DROPOFF_LOCATION_ID,
    PAYMENT_ID,
    VENDOR_ID_SURROGATE,
    PASSENGER_COUNT,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    CBD_CONGESTION_FEE,
    PICKUP_DATETIME,
    DROPOFF_DATETIME
)
SELECT
    dd.DATE_ID,
    pul.LOCATION_ID         AS PICKUP_LOCATION_ID,
    dol.LOCATION_ID         AS DROPOFF_LOCATION_ID,
    dp.PAYMENT_ID,
    dv.VENDOR_ID_SURROGATE,
    s.PASSENGER_COUNT,
    s.TRIP_DISTANCE,
    s.FARE_AMOUNT,
    s.EXTRA,
    s.MTA_TAX,
    s.TIP_AMOUNT,
    s.TOLLS_AMOUNT,
    s.IMPROVEMENT_SURCHARGE,
    s.TOTAL_AMOUNT,
    s.CONGESTION_SURCHARGE,
    s.AIRPORT_FEE,
    s.CBD_CONGESTION_FEE,
    s.TPEP_PICKUP_DATETIME,
    s.TPEP_DROPOFF_DATETIME
FROM TAXI_NYC.TAXI_SILVER.TAXI_PRATA AS s
LEFT JOIN TAXI_NYC.TAXI_GOLD.DIM_DATA AS dd
    ON DATE(s.TPEP_PICKUP_DATETIME) = dd.DATE_VALUE
LEFT JOIN TAXI_NYC.TAXI_GOLD.DIM_LOCATION AS pul
    ON TRY_TO_NUMBER(s.PU_LOCATION_ID) = pul.LOCATION_ID
LEFT JOIN TAXI_NYC.TAXI_GOLD.DIM_LOCATION AS dol
    ON TRY_TO_NUMBER(s.DO_LOCATION_ID) = dol.LOCATION_ID
LEFT JOIN TAXI_NYC.TAXI_GOLD.DIM_PAYEMENT AS dp
    ON s.PAYMENT_TYPE = dp.PAYMENT_CODE
LEFT JOIN TAXI_NYC.TAXI_GOLD.DIM_VENDOR AS dv
    ON s.VENDOR_ID = dv.VENDOR_CODE;
